//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * 
        ///from tbl_stock_code 
        ///where stockCode = &apos;{0}&apos; and stockName = &apos;{1}&apos;.
        /// </summary>
        internal static string getStockCode {
            get {
                return ResourceManager.GetString("getStockCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from tbl_stock_daily
        ///where inqDate = &apos;{0}&apos; and stockCode = &apos;{1}&apos;.
        /// </summary>
        internal static string getStockDailyInfo {
            get {
                return ResourceManager.GetString("getStockDailyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into tbl_stock_code(stockCode, stockName, createdDate) values(&apos;{0}&apos;,&apos;{1}&apos;,NOW());.
        /// </summary>
        internal static string insertStockCode {
            get {
                return ResourceManager.GetString("insertStockCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into tbl_stock_daily(
        ///inqDate
        ///, stockCode
        ///, stockName
        ///, currentPrice
        ///, traffic
        ///, diffBefore
        ///, upDownRate
        ///, createdDate
        ///)
        ///values
        ///( 
        ///&apos;{0}&apos;
        ///,&apos;{1}&apos;
        ///,&apos;{2}&apos;
        ///,&apos;{3}&apos;
        ///,&apos;{4}&apos;
        ///,&apos;{5}&apos;
        ///,&apos;{6}&apos;
        ///, NOW()
        ///).
        /// </summary>
        internal static string insertStockDaily {
            get {
                return ResourceManager.GetString("insertStockDaily", resourceCulture);
            }
        }
    }
}
